/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSvgRouteImport } from './routes/api/svg'
import { Route as ApiChartRouteImport } from './routes/api/chart'
import { Route as OwnerRepoRouteImport } from './routes/$owner.$repo'
import { Route as ApiSvgOwnerRepoRouteImport } from './routes/api/svg.$owner.$repo'
import { Route as ApiChartOwnerRepoRouteImport } from './routes/api/chart.$owner.$repo'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSvgRoute = ApiSvgRouteImport.update({
  id: '/api/svg',
  path: '/api/svg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChartRoute = ApiChartRouteImport.update({
  id: '/api/chart',
  path: '/api/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSvgOwnerRepoRoute = ApiSvgOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => ApiSvgRoute,
} as any)
const ApiChartOwnerRepoRoute = ApiChartOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => ApiChartRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$owner/$repo': typeof OwnerRepoRoute
  '/api/chart': typeof ApiChartRouteWithChildren
  '/api/svg': typeof ApiSvgRouteWithChildren
  '/api/chart/$owner/$repo': typeof ApiChartOwnerRepoRoute
  '/api/svg/$owner/$repo': typeof ApiSvgOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$owner/$repo': typeof OwnerRepoRoute
  '/api/chart': typeof ApiChartRouteWithChildren
  '/api/svg': typeof ApiSvgRouteWithChildren
  '/api/chart/$owner/$repo': typeof ApiChartOwnerRepoRoute
  '/api/svg/$owner/$repo': typeof ApiSvgOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$owner/$repo': typeof OwnerRepoRoute
  '/api/chart': typeof ApiChartRouteWithChildren
  '/api/svg': typeof ApiSvgRouteWithChildren
  '/api/chart/$owner/$repo': typeof ApiChartOwnerRepoRoute
  '/api/svg/$owner/$repo': typeof ApiSvgOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$owner/$repo'
    | '/api/chart'
    | '/api/svg'
    | '/api/chart/$owner/$repo'
    | '/api/svg/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$owner/$repo'
    | '/api/chart'
    | '/api/svg'
    | '/api/chart/$owner/$repo'
    | '/api/svg/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$owner/$repo'
    | '/api/chart'
    | '/api/svg'
    | '/api/chart/$owner/$repo'
    | '/api/svg/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  OwnerRepoRoute: typeof OwnerRepoRoute
  ApiChartRoute: typeof ApiChartRouteWithChildren
  ApiSvgRoute: typeof ApiSvgRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/svg': {
      id: '/api/svg'
      path: '/api/svg'
      fullPath: '/api/svg'
      preLoaderRoute: typeof ApiSvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chart': {
      id: '/api/chart'
      path: '/api/chart'
      fullPath: '/api/chart'
      preLoaderRoute: typeof ApiChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/svg/$owner/$repo': {
      id: '/api/svg/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/api/svg/$owner/$repo'
      preLoaderRoute: typeof ApiSvgOwnerRepoRouteImport
      parentRoute: typeof ApiSvgRoute
    }
    '/api/chart/$owner/$repo': {
      id: '/api/chart/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/api/chart/$owner/$repo'
      preLoaderRoute: typeof ApiChartOwnerRepoRouteImport
      parentRoute: typeof ApiChartRoute
    }
  }
}

interface ApiChartRouteChildren {
  ApiChartOwnerRepoRoute: typeof ApiChartOwnerRepoRoute
}

const ApiChartRouteChildren: ApiChartRouteChildren = {
  ApiChartOwnerRepoRoute: ApiChartOwnerRepoRoute,
}

const ApiChartRouteWithChildren = ApiChartRoute._addFileChildren(
  ApiChartRouteChildren,
)

interface ApiSvgRouteChildren {
  ApiSvgOwnerRepoRoute: typeof ApiSvgOwnerRepoRoute
}

const ApiSvgRouteChildren: ApiSvgRouteChildren = {
  ApiSvgOwnerRepoRoute: ApiSvgOwnerRepoRoute,
}

const ApiSvgRouteWithChildren =
  ApiSvgRoute._addFileChildren(ApiSvgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  OwnerRepoRoute: OwnerRepoRoute,
  ApiChartRoute: ApiChartRouteWithChildren,
  ApiSvgRoute: ApiSvgRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
